[package]
name = "near-flat-storage"
version = "0.0.0"
authors.workspace = true
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
borsh.workspace = true
clap.workspace = true
rayon.workspace = true

tqdm = "0.4.4"

near-chain = { path = "../../chain/chain" }
near-chain-configs = { path = "../../core/chain-configs" }

near-epoch-manager = { path = "../../chain/epoch-manager" }
near-primitives = { path = "../../core/primitives" }
near-store = { path = "../../core/store" }
nearcore = { path = "../../nearcore" }
