[package]
name = "wallet-contract"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A placeholder implementation of the Wallet Contract."
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hex.workspace = true
serde_json.workspace = true
near-sdk.workspace = true
rlp.workspace = true

[features]
nightly = []
