[package]
name = "state-sync"
version = "0.0.0"
authors.workspace = true
publish = false
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

near-chain = { path = "../../chain/chain"}
near-chain-configs = { path = "../../core/chain-configs" }
near-primitives = { path = "../../core/primitives" }
node-runtime = { path = "../../runtime/runtime" }
near-o11y = { path = "../../core/o11y" }
near-store = { path = "../../core/store" }
nearcore = { path = "../../nearcore" }
near-stdx = { path = "../../utils/stdx"}


[features]
nightly = [
  "nightly_protocol",
  "nearcore/nightly",
  "near-store/nightly",
  "near-chain/nightly",
]
nightly_protocol = ["nearcore/nightly_protocol"]
